% clc
% close all

condition_field_name_in_series_matrix = '!Sample_characteristics_name';
first_condition = {'CD4'};
second_condition = {'B Cell'};
condition_names = [first_condition, second_condition];
first_data_threshold = 4;
second_data_threshold = 4;
dataset1_name_in_legend = 'H1';
dataset2_name_in_legend = 'H2';
series_matrix1_filename =  'newGSE60424_series_matrix';
series_matrix2_filename ='newGSE107011_series_matrix';


exptable1_filename = 'human1_pre_norm';
exptable2_filename = 'human2_pre_norm';
title_ext = 'GSE60424(H1) and GSE107011(H2) before normalization';
filenames_ext = 'GSE60424_GSE107011_pre_norm';
run_estimation(exptable1_filename, series_matrix1_filename, dataset1_name_in_legend,...
                        exptable2_filename, series_matrix2_filename,dataset2_name_in_legend,...
                        condition_field_name_in_series_matrix, first_condition, second_condition,...
                        first_data_threshold, second_data_threshold,...
                        filenames_ext, title_ext)

exptable1_filename = 'human1_cmaes_threshold';
exptable2_filename = 'human2_cmaes_threshold';
title_ext = 'GSE60424(H1) and GSE107011(H2) after CMAES with threshold=0.7';
filenames_ext = 'GSE60424_GSE107011_cmaes_threshold';
run_estimation(exptable1_filename, series_matrix1_filename, dataset1_name_in_legend,...
                        exptable2_filename, series_matrix2_filename,dataset2_name_in_legend,...
                        condition_field_name_in_series_matrix, first_condition, second_condition,...
                        first_data_threshold, second_data_threshold,...
                        filenames_ext, title_ext)

exptable1_filename = 'human1_cmaes';
exptable2_filename = 'human2_cmaes';
title_ext = 'GSE60424(H1) and GSE107011(H2) after CMAES with threshold=0';
filenames_ext = 'GSE60424_GSE107011_cmaes';
run_estimation(exptable1_filename, series_matrix1_filename, dataset1_name_in_legend,...
                        exptable2_filename, series_matrix2_filename,dataset2_name_in_legend,...
                        condition_field_name_in_series_matrix, first_condition, second_condition,...
                        first_data_threshold, second_data_threshold,...
                        filenames_ext, title_ext)

exptable1_filename = 'human1_after_EB';
exptable2_filename = 'human2_after_EB';
title_ext = 'between GSE60424(H1) and GSE107011(H2) after EB';
filenames_ext = 'GSE60424_GSE107011_EB';
run_estimation(exptable1_filename, series_matrix1_filename, dataset1_name_in_legend,...
                        exptable2_filename, series_matrix2_filename,dataset2_name_in_legend,...
                        condition_field_name_in_series_matrix, first_condition, second_condition,...
                        first_data_threshold, second_data_threshold,...
                        filenames_ext, title_ext)

exptable1_filename = 'human1_afterXPN';
exptable2_filename = 'human2_afterXPN';
title_ext = 'GSE60424(H1) and GSE107011(H2) after XPN';
filenames_ext = 'GSE60424_GSE107011_XPN';
run_estimation(exptable1_filename, series_matrix1_filename, dataset1_name_in_legend,...
                        exptable2_filename, series_matrix2_filename,dataset2_name_in_legend,...
                        condition_field_name_in_series_matrix, first_condition, second_condition,...
                        first_data_threshold, second_data_threshold,...
                        filenames_ext, title_ext)