function [samples_name_human_cond1, samples_name_human_cond2,...
    samples_name_mouse_cond1, samples_name_mouse_cond2] = ...
                    extract_samples_and_build_group_tables(human_series_table, mouse_series_table,...
                                                           condition_field_name_in_series_matrix,...
                                                           condition_names)
	
    [samples_name_human_cond1, samples_name_human_cond2] = extract_samples(human_series_table,...
                                                                 condition_field_name_in_series_matrix,...
                                                                condition_names);

    [samples_name_mouse_cond1, samples_name_mouse_cond2] = extract_samples(mouse_series_table,...
                                                                 condition_field_name_in_series_matrix,...
                                                                condition_names);

    samples_name_human_cond1 = samples_name_human_cond1(1,:);
    samples_name_human_cond2 = samples_name_human_cond2(1,:);
    samples_name_mouse_cond1 = samples_name_mouse_cond1(1,:);
    samples_name_mouse_cond2 = samples_name_mouse_cond2(1,:);
end