source("dwd\\functions.R")
source("dwd\\dwd.R")
source("adjustWithDWD.R")
adjustWithDWD("1human_pre_norm.txt", "1mouse_pre_norm.txt")
adjustWithDWD("2human_pre_norm.txt", "2mouse_pre_norm.txt")
adjustWithDWD("3human_pre_norm.txt", "3mouse_pre_norm.txt")
adjustWithDWD("4human_pre_norm.txt", "4mouse_pre_norm.txt")
adjustWithDWD("human1_pre_norm.txt", "human2_pre_norm.txt")
adjustWithDWD("mouse1_pre_norm.txt", "mouse2_pre_norm.txt")